/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripleWhaleRouteImport } from './routes/triple-whale'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as StoreRouteImport } from './routes/store'
import { Route as OverviewDashboardRouteImport } from './routes/overview-dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as AccountingRouteImport } from './routes/accounting'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLogoutRouteImport } from './routes/auth.logout'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiSyncRouteImport } from './routes/api.sync'
import { Route as ApiJorttRouteImport } from './routes/api.jortt'
import { Route as ApiShopifyInstallRouteImport } from './routes/api.shopify.install'
import { Route as ApiShopifyCallbackRouteImport } from './routes/api.shopify.callback'
import { Route as ApiPublicSyncRouteImport } from './routes/api.public.sync'
import { Route as ApiPublicEnvCheckRouteImport } from './routes/api.public.env-check'
import { Route as ApiJorttConnectRouteImport } from './routes/api.jortt.connect'
import { Route as ApiJorttCallbackRouteImport } from './routes/api.jortt.callback'
import { Route as ApiAuthXeroRouteImport } from './routes/api.auth.xero'
import { Route as ApiAuthJorttRouteImport } from './routes/api.auth.jortt'
import { Route as ApiAuthXeroCallbackRouteImport } from './routes/api.auth.xero.callback'

const TripleWhaleRoute = TripleWhaleRouteImport.update({
  id: '/triple-whale',
  path: '/triple-whale',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewDashboardRoute = OverviewDashboardRouteImport.update({
  id: '/overview-dashboard',
  path: '/overview-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingRoute = AccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncRoute = ApiSyncRouteImport.update({
  id: '/api/sync',
  path: '/api/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJorttRoute = ApiJorttRouteImport.update({
  id: '/api/jortt',
  path: '/api/jortt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopifyInstallRoute = ApiShopifyInstallRouteImport.update({
  id: '/api/shopify/install',
  path: '/api/shopify/install',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopifyCallbackRoute = ApiShopifyCallbackRouteImport.update({
  id: '/api/shopify/callback',
  path: '/api/shopify/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncRoute = ApiPublicSyncRouteImport.update({
  id: '/api/public/sync',
  path: '/api/public/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEnvCheckRoute = ApiPublicEnvCheckRouteImport.update({
  id: '/api/public/env-check',
  path: '/api/public/env-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJorttConnectRoute = ApiJorttConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => ApiJorttRoute,
} as any)
const ApiJorttCallbackRoute = ApiJorttCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiJorttRoute,
} as any)
const ApiAuthXeroRoute = ApiAuthXeroRouteImport.update({
  id: '/api/auth/xero',
  path: '/api/auth/xero',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthJorttRoute = ApiAuthJorttRouteImport.update({
  id: '/api/auth/jortt',
  path: '/api/auth/jortt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthXeroCallbackRoute = ApiAuthXeroCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthXeroRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/overview-dashboard': typeof OverviewDashboardRoute
  '/store': typeof StoreRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/triple-whale': typeof TripleWhaleRoute
  '/api/jortt': typeof ApiJorttRouteWithChildren
  '/api/sync': typeof ApiSyncRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/api/auth/jortt': typeof ApiAuthJorttRoute
  '/api/auth/xero': typeof ApiAuthXeroRouteWithChildren
  '/api/jortt/callback': typeof ApiJorttCallbackRoute
  '/api/jortt/connect': typeof ApiJorttConnectRoute
  '/api/public/env-check': typeof ApiPublicEnvCheckRoute
  '/api/public/sync': typeof ApiPublicSyncRoute
  '/api/shopify/callback': typeof ApiShopifyCallbackRoute
  '/api/shopify/install': typeof ApiShopifyInstallRoute
  '/api/auth/xero/callback': typeof ApiAuthXeroCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/overview-dashboard': typeof OverviewDashboardRoute
  '/store': typeof StoreRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/triple-whale': typeof TripleWhaleRoute
  '/api/jortt': typeof ApiJorttRouteWithChildren
  '/api/sync': typeof ApiSyncRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/api/auth/jortt': typeof ApiAuthJorttRoute
  '/api/auth/xero': typeof ApiAuthXeroRouteWithChildren
  '/api/jortt/callback': typeof ApiJorttCallbackRoute
  '/api/jortt/connect': typeof ApiJorttConnectRoute
  '/api/public/env-check': typeof ApiPublicEnvCheckRoute
  '/api/public/sync': typeof ApiPublicSyncRoute
  '/api/shopify/callback': typeof ApiShopifyCallbackRoute
  '/api/shopify/install': typeof ApiShopifyInstallRoute
  '/api/auth/xero/callback': typeof ApiAuthXeroCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/overview-dashboard': typeof OverviewDashboardRoute
  '/store': typeof StoreRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/triple-whale': typeof TripleWhaleRoute
  '/api/jortt': typeof ApiJorttRouteWithChildren
  '/api/sync': typeof ApiSyncRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/api/auth/jortt': typeof ApiAuthJorttRoute
  '/api/auth/xero': typeof ApiAuthXeroRouteWithChildren
  '/api/jortt/callback': typeof ApiJorttCallbackRoute
  '/api/jortt/connect': typeof ApiJorttConnectRoute
  '/api/public/env-check': typeof ApiPublicEnvCheckRoute
  '/api/public/sync': typeof ApiPublicSyncRoute
  '/api/shopify/callback': typeof ApiShopifyCallbackRoute
  '/api/shopify/install': typeof ApiShopifyInstallRoute
  '/api/auth/xero/callback': typeof ApiAuthXeroCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounting'
    | '/invoices'
    | '/login'
    | '/overview-dashboard'
    | '/store'
    | '/subscriptions'
    | '/triple-whale'
    | '/api/jortt'
    | '/api/sync'
    | '/auth/callback'
    | '/auth/logout'
    | '/api/auth/jortt'
    | '/api/auth/xero'
    | '/api/jortt/callback'
    | '/api/jortt/connect'
    | '/api/public/env-check'
    | '/api/public/sync'
    | '/api/shopify/callback'
    | '/api/shopify/install'
    | '/api/auth/xero/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounting'
    | '/invoices'
    | '/login'
    | '/overview-dashboard'
    | '/store'
    | '/subscriptions'
    | '/triple-whale'
    | '/api/jortt'
    | '/api/sync'
    | '/auth/callback'
    | '/auth/logout'
    | '/api/auth/jortt'
    | '/api/auth/xero'
    | '/api/jortt/callback'
    | '/api/jortt/connect'
    | '/api/public/env-check'
    | '/api/public/sync'
    | '/api/shopify/callback'
    | '/api/shopify/install'
    | '/api/auth/xero/callback'
  id:
    | '__root__'
    | '/'
    | '/accounting'
    | '/invoices'
    | '/login'
    | '/overview-dashboard'
    | '/store'
    | '/subscriptions'
    | '/triple-whale'
    | '/api/jortt'
    | '/api/sync'
    | '/auth/callback'
    | '/auth/logout'
    | '/api/auth/jortt'
    | '/api/auth/xero'
    | '/api/jortt/callback'
    | '/api/jortt/connect'
    | '/api/public/env-check'
    | '/api/public/sync'
    | '/api/shopify/callback'
    | '/api/shopify/install'
    | '/api/auth/xero/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountingRoute: typeof AccountingRoute
  InvoicesRoute: typeof InvoicesRoute
  LoginRoute: typeof LoginRoute
  OverviewDashboardRoute: typeof OverviewDashboardRoute
  StoreRoute: typeof StoreRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  TripleWhaleRoute: typeof TripleWhaleRoute
  ApiJorttRoute: typeof ApiJorttRouteWithChildren
  ApiSyncRoute: typeof ApiSyncRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  ApiAuthJorttRoute: typeof ApiAuthJorttRoute
  ApiAuthXeroRoute: typeof ApiAuthXeroRouteWithChildren
  ApiPublicEnvCheckRoute: typeof ApiPublicEnvCheckRoute
  ApiPublicSyncRoute: typeof ApiPublicSyncRoute
  ApiShopifyCallbackRoute: typeof ApiShopifyCallbackRoute
  ApiShopifyInstallRoute: typeof ApiShopifyInstallRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/triple-whale': {
      id: '/triple-whale'
      path: '/triple-whale'
      fullPath: '/triple-whale'
      preLoaderRoute: typeof TripleWhaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview-dashboard': {
      id: '/overview-dashboard'
      path: '/overview-dashboard'
      fullPath: '/overview-dashboard'
      preLoaderRoute: typeof OverviewDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting': {
      id: '/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync': {
      id: '/api/sync'
      path: '/api/sync'
      fullPath: '/api/sync'
      preLoaderRoute: typeof ApiSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jortt': {
      id: '/api/jortt'
      path: '/api/jortt'
      fullPath: '/api/jortt'
      preLoaderRoute: typeof ApiJorttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopify/install': {
      id: '/api/shopify/install'
      path: '/api/shopify/install'
      fullPath: '/api/shopify/install'
      preLoaderRoute: typeof ApiShopifyInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopify/callback': {
      id: '/api/shopify/callback'
      path: '/api/shopify/callback'
      fullPath: '/api/shopify/callback'
      preLoaderRoute: typeof ApiShopifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync': {
      id: '/api/public/sync'
      path: '/api/public/sync'
      fullPath: '/api/public/sync'
      preLoaderRoute: typeof ApiPublicSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/env-check': {
      id: '/api/public/env-check'
      path: '/api/public/env-check'
      fullPath: '/api/public/env-check'
      preLoaderRoute: typeof ApiPublicEnvCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jortt/connect': {
      id: '/api/jortt/connect'
      path: '/connect'
      fullPath: '/api/jortt/connect'
      preLoaderRoute: typeof ApiJorttConnectRouteImport
      parentRoute: typeof ApiJorttRoute
    }
    '/api/jortt/callback': {
      id: '/api/jortt/callback'
      path: '/callback'
      fullPath: '/api/jortt/callback'
      preLoaderRoute: typeof ApiJorttCallbackRouteImport
      parentRoute: typeof ApiJorttRoute
    }
    '/api/auth/xero': {
      id: '/api/auth/xero'
      path: '/api/auth/xero'
      fullPath: '/api/auth/xero'
      preLoaderRoute: typeof ApiAuthXeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/jortt': {
      id: '/api/auth/jortt'
      path: '/api/auth/jortt'
      fullPath: '/api/auth/jortt'
      preLoaderRoute: typeof ApiAuthJorttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/xero/callback': {
      id: '/api/auth/xero/callback'
      path: '/callback'
      fullPath: '/api/auth/xero/callback'
      preLoaderRoute: typeof ApiAuthXeroCallbackRouteImport
      parentRoute: typeof ApiAuthXeroRoute
    }
  }
}

interface ApiJorttRouteChildren {
  ApiJorttCallbackRoute: typeof ApiJorttCallbackRoute
  ApiJorttConnectRoute: typeof ApiJorttConnectRoute
}

const ApiJorttRouteChildren: ApiJorttRouteChildren = {
  ApiJorttCallbackRoute: ApiJorttCallbackRoute,
  ApiJorttConnectRoute: ApiJorttConnectRoute,
}

const ApiJorttRouteWithChildren = ApiJorttRoute._addFileChildren(
  ApiJorttRouteChildren,
)

interface ApiAuthXeroRouteChildren {
  ApiAuthXeroCallbackRoute: typeof ApiAuthXeroCallbackRoute
}

const ApiAuthXeroRouteChildren: ApiAuthXeroRouteChildren = {
  ApiAuthXeroCallbackRoute: ApiAuthXeroCallbackRoute,
}

const ApiAuthXeroRouteWithChildren = ApiAuthXeroRoute._addFileChildren(
  ApiAuthXeroRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountingRoute: AccountingRoute,
  InvoicesRoute: InvoicesRoute,
  LoginRoute: LoginRoute,
  OverviewDashboardRoute: OverviewDashboardRoute,
  StoreRoute: StoreRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  TripleWhaleRoute: TripleWhaleRoute,
  ApiJorttRoute: ApiJorttRouteWithChildren,
  ApiSyncRoute: ApiSyncRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  ApiAuthJorttRoute: ApiAuthJorttRoute,
  ApiAuthXeroRoute: ApiAuthXeroRouteWithChildren,
  ApiPublicEnvCheckRoute: ApiPublicEnvCheckRoute,
  ApiPublicSyncRoute: ApiPublicSyncRoute,
  ApiShopifyCallbackRoute: ApiShopifyCallbackRoute,
  ApiShopifyInstallRoute: ApiShopifyInstallRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
